# Generated by Django 5.2.3 on 2025-07-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollresult',
            name='components_snapshot',
            field=models.JSONField(default=dict),
        ),
    ]
