# Generated by Django 5.2.3 on 2025-07-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payrollresult_components_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='upload_session',
        ),
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
