# Generated by Django 5.2.3 on 2025-07-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_remove_component_upload_session_alter_employee_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='source_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
