# Generated by Django 5.2.3 on 2025-07-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_payrollrun_archivedpayrollresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrun',
            name='run_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
